version: '3'
services:

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_USER=fastapi
    healthcheck:
      test: pg_isready -U fastapi
      interval: 5m
      timeout: 10s
      retries: 5

  fastapi:
    build: .
    container_name: fastapi
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - PG_DSN=postgresql+asyncpg://fastapi:fastapi@db:5432/fastapi
